"$schema" = 'https://starship.rs/config-schema.json'

format = """$directory\
$git_branch\
$git_status\
$git_metrics\
$c\
$golang\
$java\
$nodejs\
${custom.python}\
$rust\
$character
"""

right_format = """$time ($jobs)"""


add_newline = false

[character]
success_symbol = " [❯](bold fg:#9ece6a)"

[time]
disabled = false
time_format = '%T'
style = "fg:#9ece6a"
format = "[$time]($style)"

[directory]
style = "fg:#7aa2f7"
format = "[ $path ]($style)"
truncation_length = 5
truncation_symbol = "…/"
truncate_to_repo = false

[jobs]
symbol = "\uf013"
style = "fg:#9ece6a"
format = "[ $symbol ($number)]($style)"

[c]
symbol = " "
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "fg:#f7768e"
format = '[ $symbol $branch ]($style)'

[git_status]
disabled = false
ahead = "⇡(#2ac3de)"
diverged = "(#ff9e64)"
behind = "⇣(#ff9e64)"
staged = "++(#9ece6a)"
format = '[$all_status$ahead_behind]($style)'

[git_metrics]
disabled = false

[golang]
symbol = " "
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "fg:#ff9e64"
format = '[ $symbol ($version) ]($style)'

[custom.python]
disabled = false
style = "fg:#9ece6a"
symbol = "\ue73c"
detect_files = [
  '.python-version',
  'Pipfile',
  '__init__.py',
  'pyproject.toml',
  'requirements.txt',
  'setup.py',
  'tox.ini',
]
command = """
if [[ -e .python-version ]]; then
  VENV=$(cat .python-version)
elif [[ -n "$PYENV_VIRTUAL_ENV" ]]; then
  VENV=$(basename "$PYENV_VIRTUAL_ENV")
else
  VENV=""
fi
echo $VENV
"""
format = '[ $symbol ($output )]($style)'
